services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: heartbeat
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./heartbeat/database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./heartbeat:/heartbeat

  metabase:
    image: metabase/metabase
    ports:
      - "3000:3000"
    environment:
      - MB_DB_TYPE=postgres
      - MB_DB_DBNAME=heartbeat
      - MB_DB_PORT=5432
      - MB_DB_USER=postgres
      - MB_DB_PASS=postgres
      - MB_DB_HOST=db
    volumes:
      - metabase_data:/metabase-data
  backend:
    build:
      context: ./heartbeat/backend
      dockerfile: Dockerfile
    depends_on:
      - db

volumes:
  db_data:
  metabase_data:
